version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    hostname: fireflyiiiapp
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb    
    restart: always
    hostname: fireflyiiidb
#    env_file: .db.env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
  fidi:
    image: fireflyiii/data-importer:latest
    restart: always
    env_file: .fidi.env
    environment:
      - FIREFLY_III_URL=http://fireflyiiiapp:8080
    ports:
      - 8081:8080
    depends_on:
      - app
volumes:
   firefly_iii_upload:
   firefly_iii_db: